language: php
sudo: false
dist: trusty
php:
  - '7.1'
  - '7.2'
install:
  - travis_retry composer update
script:
  - vendor/bin/phpunit tests/ --bootstrap=vendor/autoload.php --config=tests/phpunit.xml